List<String> retailers = [
  "None / Unknown",
  "Walmart",
  "Lowe's",
  "Home Depot",
  "Michaels",
  "Joann Fabrics",
  "Costco",
  "BJ's",
  "Hobby Lobby",
  "Target",
  "AC Moore",
  "Dollar Tree",
  "Amazon",
  "Office Depot/OfficeMax",
  "Staples",
  "Sam’s Club",
  "Fabric.com",
  "Dick Blick Art Materials",
  "Paper Source",
  "Joann",
  "Crate and Barrel",
  "Bed Bath & Beyond",
  "Kmart",
  "Big Lots",
  "Five Below",
  "Ross Stores",
  "TJ Maxx",
  "Marshalls",
  "Tuesday Morning",
  "At Home",
  "IKEA",
  "Wayfair",
  "Overstock",
  "Etsy",
  "AliExpress",
  "Howl Fabric",
  "Big Z Fabric",
  "Other"
];
